### ISSUE TITLE
1. Mini project 설계

### ISSUE THREAD

**Issue by LeeHannaa** [2022OSSminiproject/project1#1]
이번에 미니프로젝트 주제는 카페디저트자판기로 정해진 걸로 기억하는데 어떤 식으로 코드를 구성해 볼까요?

**Comment by 21900304** [comment]
첫번째로 판매자와 구매자를 나누는 함수가 필요할 거 같습니다!. 그리고 CRUD 함수를 만들면 될 거 같습니다!

**Comment by LeeHannaa** [comment]
그러면 기본적으로 디저트 품목 확인하는 함수는 양측에 다 필요할 것 같고 판매자 측에는 디저트 품목 수정,삭제하는 함수도 있으면 좋을 것 같아요

**Comment by 21900304** [comment]
넵넵 추가적으로 구매자를 선택했을 때 디저트의 디카페인, 당도 등 취향을 선택할 수 있는 함수를 만들었으면 좋겠어요

**Comment by LeeHannaa** [comment]
오 좋은 것 같아요! 그리고 소비자 측에 포인트(?) 도장(?) 그거 확인하는 시스템도 있으면 좋을 것 같아요

**Comment by 21900304** [comment]
그럼 함수이름을 정해보겠습니다

**Comment by LeeHannaa** [comment]
넵넵 좋아요!
