### ISSUE TITLE
함수 수정 및 분배

### ISSUE THREAD

**Issue by LeeHannaa** [2022OSSminiproject/project1#12]
안녕하세요! 
나머지 함수들이랑 기존 CRUD함수 수정에 대해서 이야기해볼까해요!

0. 이번에 수정한 사항
load함수 경고 뜨는 부분 수정해서 다시 올려놨습니다.

1. 수정 요청사항
-delete함수에서 지정된 음료 목록만 지울 수 있게 변경했으면 좋겠어요.
-변수 만드실 때 옆에 간단하게 어떤 역할을 하는 변수인지 주석으로 달아주시면 감사하겠습니다.
(ex, index와 count가 각각 어떤 값을 받는지)
-판매자가 음료 추가할 때 테이크아웃 여부는 관리할 필요 없어보여요. 그 부분은 파일 안에 따로 안 만들고 구매자가 구매할 때 일시적으로 넣어주면 될 것 같아요. 그리고 도장도 관리할 필요 없는 것 같아요(?)

2. 코드 내용
-구매자가 도장을 찍을 때 판매자의 정보가 담겨야 몇회 찍었는지 기록이 남을 것 같은데 구매자가 음료 목록 기록해놓은 텍스트 파일, 판매자가 이름이랑 도장 기록해 놓을 텍스트파일 이렇게 두개로 나누면 좋을 것 같은데 의견 남겨주세요!

3. 나머지 함수들
void listConsumer();//소비자가 디저트 품목을 확인하고 구매를 하는 함수
void decaffeine();// 소비자가 구매를 할 때 디카페인, 당도 등 자신의 취향을 결정하게 도와주는 함수
int pointStemp();//소비자에게 스탬프를 찍어, 몇 회 이상 방문하였는지 확인할 수 있는 함수
int takeOut();// 소비자가 매장 내에서 음료를 마실지, 포장할 지 정해주는 함수
이렇게 크게 4개가 남은 것 같은데 소비자가 디저트 품목을 확인하고 구매하는 함수를 만드시면 나머지 3개를 제가 만드는 걸로 할까요? 이 부분도 의견 남겨주세요!(어떻게 분배할지)

**Comment by 21900304** [comment]
넵넵 수정 사항 확인하였고 구매자가 스탬프를 몇 회 찍었는지 텍스트 파일과 도장을 기록해 놓는 텍스트 파일을 구분하겠습니다!!
각 코드의 주석은 이번 주 일요일까지 수정하여 pr 넣겠습니다!

**Comment by LeeHannaa** [comment]
코드 주석은 없어도 될 것 같은데 각 변수 주석은 내일까지 해주실 수 있나요? 저도 함수 만들때 바로바로 보고 하면 편할 것 같아서요..!

**Comment by LeeHannaa** [comment]
그리고 방금 코드를 다시 봤는데 updataDessert이 코드도 어떤 음료(몇번째)를 수정할지 선택하고 그 목록에 있는 정보를 수정하는걸로 해야할 것 같습니다!

**Comment by 21900304** [comment]
넵넵 주석은 내일까지 수정하여 커밋하고 updata함수도 금요일내로 수정해서 올리겠습니다!

**Comment by 21900304** [comment]
나머지 함수 구현은 금요일 수업 시간에 만나서 상의 해보면 좋을 것 같습니다!!!

**Comment by LeeHannaa** [comment]
네! 알겠습니다!!
