### ISSUE TITLE
수정사항

### ISSUE THREAD

**Issue by LeeHannaa** [2022OSSminiproject/project1#14]
안녕하세요 이번에 제가 수정한 부분이 너무 많아서 여기서 간단하게 설명드릴게요! 
1. 일단 menu_list배열 변수에서 포인터 배열변수로 변경해서 이 변수 사용한 부분은 전부 다 실행 되도록 수정해 놨습니다.
2.  load,save함수 다 실행 되도록 변경했습니다.
3. 헤더파일 함수에 변수 다 넣어줬습니다.(수정 부분 보시면 이해가실 거에요!)
4. readDessert함수에 price범위 수정 했습니다.
5. 변수 타입때문에 실행 안되었던 부분 다 수정했고 잘 실행되는 거 보고 push했습니다.

**Comment by LeeHannaa** [comment]
이제 함수 4개 남은 부분만 구현하면 될 것 같습니다.
오늘 말했 듯이 2개씩 구현하면 될 것 같고 제가 변경해놓은 변수 타입을 잘 보고 코드를 작성해주시길 바랍니다!! 조금이라도 이해 안되는 부분 있으면 언제든지 연락주세요!

**Comment by LeeHannaa** [comment]
그리고 손님 정보 저장하는 struct랑 파일 로드,저장 제가 만들게요!

**Comment by 21900304** [comment]
나머지 2개는 제가 작성하여 pr 하겠습니다!!!
