### ISSUE TITLE
이번에 구현한 함수

### ISSUE THREAD

**Issue by LeeHannaa** [2022OSSminiproject/project1#15]
안녕하세요 이번에 구현한 함수에 대해서 간단히 설명드리겠습니다.

이번에 구매자일때 main함수 다 만들어 놨고, 학우님이 작성해야 할 부분 틀도 다 만들어 놔서 그 틀대로 하시면 되겠습니다!
그리고 selectMenu_User(),pointStemp(),User_LoadDate(),User_SaveDate(),takeOut()함수 구현 했습니다. 다 잘 작동하는데 한번 확인해 주시길 바랍니다! 
(selectMenu_User(),User_LoadDate(),User_SaveDate() 함수들은 코드를 작성하다 보니 필요하다고 판단해 추가로 작성한 것입니다)

제가 코드 안에 어떤 방향으로 코드를 짜면 좋을지 다 주석으로 적어놨습니다. 혹시 보시고 다른 의견 있으시면 언제든지 알려주세요!

**Comment by 21900304** [comment]
넵넵 수정사항 확인하였고, 저도 학우님이 써주신 주석대로 맞춰서 코드를 작성하도록 하겠습니다!

**Comment by 21900304** [comment]
1. 주석 추가 2. 몇 번을 삭제해야하는 함수 추가 3. 스탬프와 음료 취식 변수를 제거(구매자에게 추가할거에요!
이렇게 수정하여 pr 보냈습니다!

**Comment by 21900304** [comment]
마지막 함수를 추가하여 pr 보냈습니다!! 모든 함수 정상적으로 실행되고 스크린 샷을 메일로 보내드리겠습니다!

**Comment by LeeHannaa** [comment]
네 감사합니다!
