### ISSUE TITLE
수정 요청

### ISSUE THREAD

**Issue by LeeHannaa** [2022OSSminiproject/project1#17]
이번에 코드 작성하신 부분에서 컴파일 전에 경고가 뜹니다! 확인하고 수정 부탁드립니다
![image](https://user-images.githubusercontent.com/103620720/168420018-0a59d7d4-a51d-4fd6-9368-6c8d1a98abe7.png)

**Comment by 21900304** [comment]
말씀하신 수정 사항 수정하여 다시 pr 보냈습니다!!!

**Comment by LeeHannaa** [comment]
감사합니다!
