### ISSUE TITLE
코드 나누기

### ISSUE THREAD

**Issue by LeeHannaa** [2022OSSminiproject/project1#9]
안녕하세요! 저희 코드 어떻게 나눠서 짜면 좋을까요?

**Comment by 21900304** [comment]
일단 기본적인 CRUD파일을 만들고 그 이후에 판매자와 구매자를 설정하는 함수를 만들면 좋을 것 같아요!

**Comment by LeeHannaa** [comment]
load함수랑 save함수는 간단하니깐 제가 내일까지 업로드해놓을게요! 그 처음에 menu부분 만들어 주실 수 있나요? 손님이랑 사장(?) 이렇게 먼저 나누고 손님일때 메뉴 따로 사장일 때 메뉴 따로 해서 만들어 놓으면 그 뒤로 좀 더 체계적으로 할 수 있을 것 같아요!

**Comment by LeeHannaa** [comment]
1번이면 판매자, 2번이면 구매자로 나눠서 시작하면 좋을 것 같아요!

**Comment by 21900304** [comment]
넵넵 일단 head 파일과 텍스트 파일 그리고 main 파일을 구현 하면 좋을 것 같습니다

**Comment by LeeHannaa** [comment]
제가 로드 함수랑 세이브 함수 구현하고 헤더파일 만들어 놨는데 변수랑 타입 확인하고 코드짤때 참고해주세요! 그리고 CRUD 만드시고 제품 하나 추가해서 파일 로드, 저장 함수가 잘 작동 되는지 확인해보시고 알려주시면 감사하겠습니다!

**Comment by 21900304** [comment]
제가 CRUD 파일과 selectUser, selectMenu 함수를 작성하여 pr 보냈습니다! 컴파일 결과 다 정상 작동하였습니다!

**Comment by LeeHannaa** [comment]
수고하셨습니다!
